### ISSUE TITLE
saveボタンで保存した際にエラーが表示されて保存されない

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#44]
優先度：中（[代替の方法][1]で保存可能なため）

[1]:https://github.com/pxgrid/ui-spec-md/issues/44#issuecomment-559339148

---

`ui-spec-md edit-server -m ./uispec -d dist/edit` を実行してサーバーを立ち上げます。
表示された `http://localhost:3001/` で、編集アイコンをクリックし、テキストエリアで内容を変更し、Saveボタンをクリックしました。

ですが、ターミナルで次のエラーが発生しており、編集した内容は保存されていないようでした。

```
Error: EISDIR: illegal operation on a directory, open '/Users/geckotang/Work/PROJECT_NAME/uispec'
    at Object.openSync (fs.js:440:3)
    at Object.writeFileSync (fs.js:1265:35)
    at /Users/geckotang/Work/PROJECT_NAME/node_modules/ui-spec-md/server/editable.js:61:10
    at /Users/geckotang/Work/PROJECT_NAME/node_modules/ui-spec-md/server/editable.js:68:7
    at Layer.handle [as handle_request] (/Users/geckotang/Work/PROJECT_NAME/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/geckotang/Work/PROJECT_NAME/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/geckotang/Work/PROJECT_NAME/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/geckotang/Work/PROJECT_NAME/node_modules/express/lib/router/layer.js:95:5)
    at /Users/geckotang/Work/PROJECT_NAME/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/geckotang/Work/PROJECT_NAME/node_modules/express/lib/router/index.js:335:12)
```

**Comment by tomof** [comment]
@geckotang 
`ui-spec-md edit-server -m ./uispec -d dist/edit` のコマンドのオプションはそれぞれ下記の意味を持ちます。

-m : マークダウンが入っているディレクトリ
-d : 出力先のディレクトリを意味しています

Slackで教えてもらったディレクトリ状況だと、`./ui-spec`のディレクトリも `dist/edit`ディレクトリも存在しないので、目的のパスに書き換えてみてください。

**Comment by geckotang** [comment]
@tomof 

今のディレクトリ構成は次のとおりです

```
uispec/
    index.md
dist/
    edit/
package.json
package-lock.json
README.md
```

`dist/edit` ディレクトリは、存在しない場合作成されるのかな？と思っていましたが、一応自分で`dist/edit` を作ってみて、再度コマンドを実行してみましたが、保存の際に同様のエラーが発生しました。

**Comment by tomof** [comment]
例えば、http://localhost:3001/ の場合や、http://localhost:3001/foo/ のような、パスとしてindex.htmlが自動補完されるようなページで発生しているものと思われる。
サーバーとローカルのファイルパスマッチング時にこのことを考慮した作りに修正が必要。

**Comment by geckotang** [comment]
`http://localhost:3001/index.html` で編集すれば保存されるのでなおるまではそれでやります！

**Comment by tomof** [comment]
@geckotang v0.3.4にて対応しました。もし、直ってなかったらreopenしてください。
