### ISSUE TITLE
screenに存在しない画像を指定した場合のエラーメッセージをわかりやすくしてほしい

### ISSUE THREAD

**Issue by geckotang** [pxgrid/ui-spec-md#46]
優先度：低（エラーが出てもサーバーが止まるわけでないので）

---

mdのyamlブロックで、screenの値に存在しない画像のパスを指定すると次のようなエラーが表示されます。エラーが出てもローカルサーバーが止まったりはしないのでuispecを書く上での支障はありません。

```
Error: ENOENT: no such file or directory, open '/Users/geckotang/Work/PROJECT_NAME/uispec/index.png'
    at Object.openSync (fs.js:440:3)
    at syncFileToBuffer (/Users/geckotang/Work/PROJECT_NAME/node_modules/image-size/lib/index.js:79:23)
    at module.exports (/Users/geckotang/Work/PROJECT_NAME/node_modules/image-size/lib/index.js:121:18)
    at makeSvgCanvasSrc (/Users/geckotang/Work/PROJECT_NAME/node_modules/ui-spec-md/lib/build-page/make-template-context.js:43:22)
    at makeTemplateContext (/Users/geckotang/Work/PROJECT_NAME/node_modules/ui-spec-md/lib/build-page/make-template-context.js:78:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async embedHtml (/Users/geckotang/Work/PROJECT_NAME/node_modules/ui-spec-md/lib/build-page/embed-html.js:10:27)
    at async Promise.all (index 0)
    at async FSWatcher.<anonymous> (/Users/geckotang/Work/PROJECT_NAME/node_modules/ui-spec-md/server/edit-server.js:67:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/geckotang/Work/PROJECT_NAME/uispec/index.png'
}
```

エラーはエラーなのですが、私の場合だけかもしれませんが、uispecを書いているときは、画像はあとで置く想定でscreenにファイル名を指定することがあるので、エラーはヒトが読みやすい感じになっていると良いかもしれません。

> `uispec/index.png` が見つかりません

とか。

**Comment by tomof** [comment]
v0.5.14で次のようなメッセージの表示に変更しました。

```
Not found screen image file.
 screen: ./img/dummy-svg-ssss.png?highlight=...
 FullPath: /Users/tomof/project/pxgrid/ui-spec-md/public/dummies/img/dummy-svg-ssss.png
```
